### ISSUE TITLE
Files < minPartSize not uploaded correctly

### ISSUE THREAD

**Issue by sippd** [walvekarnikhil/amplify-s3-chunk-upload#7]
If the total file size is < minPartSize (as defined in StorageChunkManagedUpload) then the following JSON object encoded in base64 is uploaded to S3 instead of the file contents:
```
{"size":<file-size-in-bytes>}
```
It appears that the library uploads the fileObject itself instead of calling `slice()`.

As a workaround if the file size is < minPartSize we need to read the file in full and pass that as the fileObject to Storage.put().

**Comment by walvekarnikhil** [comment]
@sippd , checking the issue.
